CREATE TABLE `produtos` (
	`ID` INT(20) NOT NULL AUTO_INCREMENT,
	`NOME` VARCHAR(100) NOT NULL DEFAULT '' COLLATE 'utf8_unicode_ci',
	`DESCRICAO` VARCHAR(100) NOT NULL DEFAULT '' COLLATE 'utf8_unicode_ci',
	`VALOR` DOUBLE(10,2) NOT NULL DEFAULT '8.50',
	PRIMARY KEY (`ID`) USING BTREE
)
COLLATE='utf8_unicode_ci'
ENGINE=InnoDB
;
